language: cpp
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libboost-dev
      - libcairomm-1.0-dev
      - libgtkmm-2.4-dev
      - libgsl0-dev
      - libatlas-base-dev
      - ragel
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtkmm gsl ragel; fi

matrix:
  include:
    - os: linux
      compiler: gcc
      script: cmake . && make && ctest -V
    - os: linux
      compiler: clang
      script: cmake . && make && ctest -V
    - os: osx
      compiler: clang
      script: cmake . && make && ctest -V
