language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libboost-dev
      - libcairomm-1.0-dev
      - libgtkmm-2.4-dev
      - libgsl0-dev
      - libatlas-base-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gtkmm gsl; fi
script:
  - cmake . && make && make test
